export enum EmailNotificationTemplate {
  ACCESSORS_ACTION_TO_REVIEW = "ACCESSORS_ACTION_TO_REVIEW",
  ACCESSORS_ASSIGNED_TO_INNOVATION = "ACCESSORS_ASSIGNED_TO_INNOVATION",
  INNOVATORS_ACTION_REQUEST = "INNOVATORS_ACTION_REQUEST",
  QA_ORGANISATION_SUGGESTED = "QA_ORGANISATION_SUGGESTED",
}
