export enum InnovationStatus {
  WAITING_NEEDS_ASSESSMENT = "WAITING_NEEDS_ASSESSMENT",
  IN_PROGRESS = "IN_PROGRESS",
  NEEDS_ASSESSMENT_REVIEW = "NEEDS_ASSESSMENT_REVIEW",
  ABANDONED = "ABANDONED",
  COMPLETE = "COMPLETE",
}

export enum InnovationActionStatus {
  REQUESTED = "REQUESTED",
  STARTED = "STARTED",
  CONTINUE = "CONTINUE",
  IN_REVIEW = "IN_REVIEW",
  DELETED = "DELETED",
  DECLINED = "DECLINED",
  COMPLETED = "COMPLETED",
}

export enum InnovationSectionStatus {
  NOT_STARTED = "NOT_STARTED",
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
}

export enum InnovationSupportStatus {
  UNNASSIGNED = "UNNASSIGNED",
  FURTHER_INFO_REQUIRED = "FURTHER_INFO_REQUIRED",
  WAITING = "WAITING",
  NOT_YET = "NOT_YET",
  ENGAGING = "ENGAGING",
  UNSUITABLE = "UNSUITABLE",
  WITHDRAWN = "WITHDRAWN",
  COMPLETE = "COMPLETE",
}

export enum InnovationSectionCatalogue {
  INNOVATION_DESCRIPTION = "INNOVATION_DESCRIPTION",
  VALUE_PROPOSITION = "VALUE_PROPOSITION",
  UNDERSTANDING_OF_NEEDS = "UNDERSTANDING_OF_NEEDS",
  UNDERSTANDING_OF_BENEFITS = "UNDERSTANDING_OF_BENEFITS",
  EVIDENCE_OF_EFFECTIVENESS = "EVIDENCE_OF_EFFECTIVENESS",
  MARKET_RESEARCH = "MARKET_RESEARCH",
  INTELLECTUAL_PROPERTY = "INTELLECTUAL_PROPERTY",
  REGULATIONS_AND_STANDARDS = "REGULATIONS_AND_STANDARDS",
  CURRENT_CARE_PATHWAY = "CURRENT_CARE_PATHWAY",
  TESTING_WITH_USERS = "TESTING_WITH_USERS",
  COST_OF_INNOVATION = "COST_OF_INNOVATION",
  COMPARATIVE_COST_BENEFIT = "COMPARATIVE_COST_BENEFIT",
  REVENUE_MODEL = "REVENUE_MODEL",
  IMPLEMENTATION_PLAN = "IMPLEMENTATION_PLAN",
}
