export enum NotifContextType {
  INNOVATION = "INNOVATION",
  COMMENT = "COMMENT",
  ACTION = "ACTION",
  NEEDS_ASSESSMENT = "NEEDS_ASSESSMENT",
  SUPPORT = "SUPPORT",
}

export enum NotifContextDetail {
  LOCK_USER = "LOCK_USER",
  COMMENT_CREATION = "COMMENT_CREATION",
  COMMENT_REPLY = "COMMENT_REPLY",
  ACTION_CREATION = "ACTION_CREATION",
  ACTION_UPDATE = "ACTION_UPDATE",
  NEEDS_ASSESSMENT_COMPLETED = "NEEDS_ASSESSMENT_COMPLETED",
  NEEDS_ASSESSMENT_ORGANISATION_SUGGESTION = "NEEDS_ASSESSMENT_ORGANISATION_SUGGESTION",
  INNOVATION_SUBMISSION = "INNOVATION_SUBMISSION",
  SUPPORT_STATUS_UPDATE = "SUPPORT_STATUS_UPDATE",
}

export enum NotificationActionType {
  ACTION_CREATION = "ACTION_CREATION", // tested
  ACTION_UPDATE = "ACTION_UPDATE", // tested
  INNOVATOR_COMMENT_RECEIVED = "INNOVATOR_COMMENT_RECEIVED", //tested
  ACCESSOR_COMMENT_RECEIVED = "ACCESSORS_COMMENT_RECEIVED", //tested
  INNOVATOR_SUPPORT_STATUS_UPDATE = "INNOVATOR_SUPPORT_STATUS_UPDATE", //tested
  ACCESSOR_SUPPORT_STATUS_UPDATE = "ACCESSORS_SUPPORT_STATUS_UPDATE", //tested
  NA_SUPPORT_STATUS_UPDATE = "NA_SUPPORT_STATUS_UPDATE", //*
  LOCK_USER = "LOCK_USER",
  INNOVATION_USER_LOCK = "INNOVATION_USER_LOCK",
  INNOVATION_SUBMITED = "INNOVATION_SUBMITED", // tested
  INNOVATION_ARCHIVED = "INNOVATION_ARCHIVED",
  QA_NEEDS_ASSESSMENT_COMPLETED = "QA_NEEDS_ASSESSMENT_COMPLETED", // tested
  INNOVATOR_NEEDS_ASSESSMENT_COMPLETED = "INNOVATOR_NEEDS_ASSESSMENT_COMPLETED", // tested
  INNOVATOR_ORGANISATION_SUGGESTION = "INNOVATOR_ORGANISATION_SUGGESTION", // tested
  QA_INNOVATION_SUGGESTION = "QA_INNOVATION_SUGGESTION",
  ADMINS_LOGIN_VALIDATION = "ADMINS_LOGIN_VALIDATION",
  INNOVATOR_ACCOUNT_CREATION = "INNOVATOR_ACCOUNT_CREATION",
  ACCESSOR_UNIT_CHANGE = "ACCESSOR_UNIT_CHANGE",
  INNOVATOR_TRANSFER_OWNERSHIP_EXISTING_USER = "INNOVATOR_TRANSFER_OWNERSHIP_EXISTING_USER", //tem de dar para enviar para um email em especifico
  INNOVATOR_TRANSFER_OWNERSHIP_NEW_USER = "INNOVATOR_TRANSFER_OWNERSHIP_NEW_USER", //tem de dar para enviar para um email em especifico
  INNOVATOR_TRANSFER_OWNERSHIP_CONFIRMATION = "INNOVATOR_TRANSFER_OWNERSHIP_CONFIRMATION", //*
}

export type NotifContextPayloadType = {
  id: string;
  type: NotifContextType;
};

export type NotificationParamsType = {};
