export enum NotifContextType {
  INNOVATION = "INNOVATION",
  COMMENT = "COMMENT",
  ACTION = "ACTION",
  NEEDS_ASSESSMENT = "NEEDS_ASSESSMENT",
  SUPPORT = "SUPPORT",
}

export enum NotifContextDetail {
  LOCK_USER = "LOCK_USER",
  COMMENT_CREATION = "COMMENT_CREATION",
  COMMENT_REPLY = "COMMENT_REPLY",
  ACTION_CREATION = "ACTION_CREATION",
  ACTION_UPDATE = "ACTION_UPDATE",
  NEEDS_ASSESSMENT_COMPLETED = "NEEDS_ASSESSMENT_COMPLETED",
  NEEDS_ASSESSMENT_ORGANISATION_SUGGESTION = "NEEDS_ASSESSMENT_ORGANISATION_SUGGESTION",
  INNOVATION_SUBMISSION = "INNOVATION_SUBMISSION",
  SUPPORT_STATUS_UPDATE = "SUPPORT_STATUS_UPDATE",
}

export enum NotificationActionType {
  ACTION_CREATION = "ACTION_CREATION",
  ACTION_UPDATE = "ACTION_UPDATE",
  COMMENT_CREATION = "COMMENT_CREATION",
  NEEDS_ASSESSMENT_COMPLETED = "NEEDS_ASSESSMENT_COMPLETED",
  INNOVATOR_ACCOUNT_CREATION = "INNOVATOR_ACCOUNT_CREATION",
  INNOVATION_SUBMITED = "INNOVATION_SUBMITED",
  INNOVATION_ARCHIVED = "INNOVATION_ARCHIVED",
  INNOVATION_SUPPORT_STATUS_UPDATE = "INNOVATION_SUPPORT_STATUS_UPDATE",
  INNOVATION_TRANSFER_OWNERSHIP_CREATION = "INNOVATION_TRANSFER_OWNERSHIP_CREATION",
  INNOVATION_TRANSFER_OWNERSHIP_COMPLETED = "INNOVATION_TRANSFER_OWNERSHIP_COMPLETED",
  INNOVATION_USER_LOCK = "INNOVATION_USER_LOCK",
  LOCK_USER = "LOCK_USER",
  QA_INNOVATION_SUGGESTION = "QA_INNOVATION_SUGGESTION",
  SLS_VALIDATION = "SLS_VALIDATION",
  ACCESSOR_UNIT_CHANGE = "ACCESSOR_UNIT_CHANGE",
}

export type NotifContextPayloadType = {
  id: string;
  type: NotifContextType;
};

export type NotificationParamsType = {};
