export enum UserType {
  ADMIN = "ADMIN",
  INNOVATOR = "INNOVATOR",
  ACCESSOR = "ACCESSOR",
  ASSESSMENT = "ASSESSMENT",
}

export enum ServiceRole {
  ADMIN = "ADMIN",
  SERVICE_TEAM = "SERVICE_TEAM",
}

export enum NotificationContextType {
  INNOVATION = "INNOVATION",
  ACTION = "ACTION",
  COMMENT = "COMMENT",
  SUPPORT = "SUPPORT",
  DATA_SHARING = "DATA_SHARING",
}
export enum NotificationAudience {
  ACCESSORS = "ACCESSORS",
  INNOVATORS = "INNOVATORS",
  QUALIFYING_ACCESSORS = "QUALIFYING_ACCESSORS",
  ASSESSMENT_USERS = "ASSESSMENT_USERS",
}
