export enum UserType {
  INNOVATOR = "INNOVATOR",
  ACCESSOR = "ACCESSOR",
  ASSESSMENT = "ASSESSMENT",
}

export enum NotificationContextType {
  INNOVATION = "INNOVATION",
  ACTION = "ACTION",
  COMMENT = "COMMENT",
}
export enum NotificationAudience {
  ACCESSORS = "ACCESSORS",
  INNOVATORS = "INNOVATORS",
  QUALIFYING_ACCESSORS = "QUALIFYING_ACCESSORS",
  ASSESSMENT_USERS = "ASSESSMENT_USERS",
}
export enum NotificationActivityType {
  COMMENT_CREATED_INNOVATOR = "COMMENT_CREATED_INNOVATOR",
  COMMENT_CREATED_ACCESSOR = "COMMENT_CREATED_ACCESSOR",
  REPLY_CREATED_INNOVATOR = "REPLY_CREATED_INNOVATOR",
  REPLY_CREATED_ACCESSOR = "REPLY_CREATED_ACCESSOR",
  ACTION_CREATED = "ACTION_CREATED",
  ACTION_UPDATED_INNOVATOR = "ACTION_UPDATED_INNOVATOR",
  ACTION_UPDATED_ACCESSOR = "ACTION_UPDATED_INNOVATOR",
  ACTION_DECLINED = "ACTION_DECLINED",
  INNOVATION_SUBMITED = "INNOVATION_SUBMITED",
  INNOVATION_ASSESSMENT_COMPLETE = "INNOVATION_ASSESSMENT_COMPLETE",
  INNOVATION_SUPPORT_CREATED = "INNOVATION_SUPPORT_CREATED",
  INNOVATION_SUPPORT_UPDATED = "INNOVATION_SUPPORT_UPDATED",
}
